### ISSUE TITLE
Setting encoder position not supported

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_seesawPeripheral#20]
Firmware currently does not support setting encoder position. Brought up here: 
https://github.com/adafruit/Adafruit_Seesaw/issues/90

```
SEESAW_ENCODER_BASE 0x11
SEESAW_ENCODER_POSITION 0x30
```

**Comment by JeremyLaurenson** [comment]
This should not be closed. This bug still affects the quad encoder.

**Comment by caternuson** [comment]
The issues is closed because the firmware has been updated to resolved the issue.

Issues due to receiving products running older firmware should be handle elsewhere. Please post in the forums:
https://forums.adafruit.com/
