### ISSUE TITLE
Encoder Support

### ISSUE THREAD

**Issue by jfurcean** [adafruit/Adafruit_seesawPeripheral#5]
This is a feature request for adding support for encoders to this library. I am looking to use the ATtiny817 breakout with seesaw ([PID 5233](https://www.adafruit.com/product/5233)) to build a board with 4 rotary encoders. It doesn't look like this library supports encoders like the [SAMD09 library ](https://github.com/adafruit/seesaw).

**Comment by ladyada** [comment]
not yet! we hope to add it, no ETA tho :)

**Comment by caternuson** [comment]
Looking at how SAMD seesaw implements this, here is my understanding, **which may be incorrect and/or incomplete**. This does not cover any of the I2C aspects handled by the active object framework.

**TLDR** = periodic polling of GPIO pins with some logic to update a counter value `AOEncoder::m_value`

**Details**:
The TC is setup up to fire an interrupt on a regular basis via a match condition. This is done in `initTimer()` in `bsp_timer.cpp` here:
 https://github.com/adafruit/seesaw/blob/c22f5b564a60885baaad7a1223e918559606b1e5/bsp/bsp_timer.cpp#L135
with the frequency set by `CONFIG_ENCODER_FREQ` which is passed in as a parameter to `initTimer()`. The default value is 5000:
https://github.com/adafruit/seesaw/blob/c22f5b564a60885baaad7a1223e918559606b1e5/include/SeesawConfig.h#L619

The TC interrupt is handled by `CONFIG_ENCODER_HANDLER` in `AOEncoder.cpp`, by being #def'd as the NVIC entry for TC2_Handler.
https://github.com/adafruit/seesaw/blob/c22f5b564a60885baaad7a1223e918559606b1e5/include/SeesawConfig.h#L611

The main encoder logic code is in the `CONFIG_ENCODER_HANDLER` ISR:
https://github.com/adafruit/seesaw/blob/c22f5b564a60885baaad7a1223e918559606b1e5/source/AOEncoder.cpp#L285

It's not very complex. It does a bulk read of the GPIO pins, compares state to previous state, and updates `AOEncoder::m_value` accordingly.

**Comment by ladyada** [comment]
i was going to add it to the gpio scanner we use for irq management. i just got super swmped with revisions

**Comment by caternuson** [comment]
Thanks. Sounds like no need for a fancy timer interrupt callback thing. Can use existing approach based on tracking `millis()`.

**Comment by jfurcean** [comment]
I created a draft PR #6. Any feedback would be appreciated.

**Comment by ladyada** [comment]
amazing work, sorry it took so long to review and merge but it's done now. whew!
